# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import generic.shortcuts


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(help_text=b'750x308px', upload_to=generic.shortcuts.dir_slug_path, verbose_name=b'\xd0\x9f\xd1\x83\xd1\x82\xd1\x8c \xd0\xba \xd0\xb8\xd0\xb7\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8e'),
        ),
    ]
