# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestbook.GuestBook'),
        ),
    ]
