# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_auto_20170406_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd'),
        ),
    ]
