# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170502_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserAuthData',
        ),
        migrations.AlterModelOptions(
            name='userauthdata',
            options={'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0430\u043a\u0442\u0438\u0432\u0430\u0446\u0438\u0438 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430', 'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0430\u043a\u0442\u0438\u0432\u0430\u0446\u0438\u0438 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u043e\u0432'},
        ),
        migrations.AlterModelTable(
            name='userauthdata',
            table='User_AuthData',
        ),
    ]
