# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170503_1912'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
