# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30, verbose_name=b'\xd0\xa0\xd0\xb5\xd0\xb3\xd0\xb8\xd0\xbe\xd0\xbd')),
            ],
            options={
                'db_table': 'AreasWork',
                'verbose_name': '\u0420\u0435\u0433\u0438\u043e\u043d \u043e\u0431\u0441\u043b\u0443\u0436\u0438\u0432\u0430\u043d\u0438\u044f',
                'verbose_name_plural': '\u0420\u0435\u0433\u0438\u043e\u043d\u044b \u043e\u0431\u0441\u043b\u0443\u0436\u0438\u0432\u0430\u043d\u0438\u044f',
            },
        ),
    ]
