# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20170410_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u0438\u043c\u044f')),
                ('position', models.CharField(max_length=30, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u0438\u043c\u044f')),
                ('contact', models.CharField(blank=True, help_text='Email, \u0442\u0435\u043b\u0435\u0444\u043e\u043d \u0438\u043b\u0438 \u043f\u0435\u0440\u0441\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u0439 \u0441\u0430\u0439\u0442', max_length=30, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f')),
                ('review', models.TextField(max_length=255, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u0438\u043c\u044f')),
                ('avatar', models.ImageField(help_text='130x130px', upload_to='employees/', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f \u0441\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0430')),
            ],
            options={
                'db_table': 'Employees',
                'verbose_name': '\u0421\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a',
                'verbose_name_plural': '\u0421\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.AlterField(
            model_name='areaswork',
            name='region',
            field=models.CharField(max_length=30, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='fourvaluescompany',
            name='desc1',
            field=models.CharField(max_length=20, verbose_name='\u041f\u0435\u0440\u0432\u0430\u044f \u0441\u0442\u0440\u043e\u043a\u0430 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='fourvaluescompany',
            name='desc2',
            field=models.CharField(max_length=20, verbose_name='\u0412\u0442\u043e\u0440\u0430\u044f \u0441\u0442\u0440\u043e\u043a\u0430 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='fourvaluescompany',
            name='number',
            field=models.IntegerField(verbose_name='\u0427\u0438\u0441\u043b\u043e'),
        ),
        migrations.AlterField(
            model_name='staticdates',
            name='description_services',
            field=models.TextField(verbose_name='\u041e\u0431\u0449\u0435\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0443\u0441\u043b\u0443\u0433'),
        ),
        migrations.AlterField(
            model_name='staticdates',
            name='history',
            field=models.TextField(verbose_name='\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='staticdates',
            name='mission',
            field=models.TextField(verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0446\u0435\u043b\u044c (\u043c\u0438\u0441\u0441\u0438\u044f) \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='staticdates',
            name='mission_img',
            field=models.ImageField(help_text='470x167px', upload_to='about/', verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0446\u0435\u043b\u044c (\u043c\u0438\u0441\u0441\u0438\u044f) \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='staticdates',
            name='value_company',
            field=models.TextField(verbose_name='\u0426\u0435\u043d\u043d\u043e\u0441\u0442\u0438 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='staticdates',
            name='who_we_are1',
            field=models.TextField(verbose_name='"\u041a\u0442\u043e \u043c\u044b?" - \u043f\u0435\u0440\u0432\u044b\u0439 \u0430\u0431\u0437\u0430\u0446'),
        ),
        migrations.AlterField(
            model_name='staticdates',
            name='who_we_are2',
            field=models.TextField(verbose_name='"\u041a\u0442\u043e \u043c\u044b?" - \u0432\u0442\u043e\u0440\u043e\u0439 \u0430\u0431\u0437\u0430\u0446'),
        ),
        migrations.AlterField(
            model_name='staticdates',
            name='year_company_opening',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='\u0413\u043e\u0434 \u043e\u0442\u043a\u0440\u044b\u0442\u0438\u044f \u0444\u0438\u0440\u043c\u044b'),
        ),
    ]
