# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20170411_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuesCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(max_length=20, verbose_name='\u0413\u043b\u0430\u0432\u043d\u044b\u0439 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('title_other', models.CharField(max_length=50, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0439 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('text', models.TextField(max_length=50, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(max_length=30, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='review',
            field=models.TextField(max_length=255, verbose_name='\u041e\u0442\u0437\u044b\u0432 \u0441\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0430'),
        ),
    ]
