# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20170411_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valuescompany',
            options={'verbose_name': '\u0426\u0435\u043d\u043d\u043e\u0441\u0442\u0438 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438', 'verbose_name_plural': '\u0426\u0435\u043d\u043d\u043e\u0441\u0442\u0438 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'},
        ),
        migrations.AlterField(
            model_name='valuescompany',
            name='text',
            field=models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
